### ISSUE TITLE
Support for button stacking

### ISSUE THREAD

**Issue by Yannick-DG** [victorqribeiro/radialMenu#1]
Hey there,

I had a question which I was wondering about. Can buttons have inner buttons? So let's say you press on a music button, would it be possible to replace all the other buttons with like Youtube, Spotify and such logo's instead of creating a new radial menu on that same position. Maybe like stacking buttons inside the primary ones, as in the end you can just JSON format it.

Trying to achieve something like this:

https://cdn.dribbble.com/users/170905/screenshots/801609/conceptidea.gif?vid=1

**Comment by victorqribeiro** [comment]
totally possible. a button is nothing more then a ICON and a CALLBACK. all you have to do is change the callback and icons based on the button you press.

**Comment by Yannick-DG** [comment]
I see, but you cannot manipulate the buttons I assume? Like as seen in the GIF, you see that they draw sort of ontop of the others. How hard is that to implement?

```
buttons: [
		{'text': '\uf053', 'action': ()=>{ },
		{'text': '\uf054', 'action': ()=>{  }, 'nestedButtons': [
                    {'text': 'Sub button 1', 'action': ()=>{  },
                    {'text': 'Sub button 2', 'action': ()=>{  },
                ]},
	]
```

Something like this for example. I looked into the code, shouldn't be hard with an extra for loop, it's a matter of replacing the visible buttons by the sub buttons and return to the main buttons upon pressing like a back button.

**Comment by Yannick-DG** [comment]
Is it also possible to set the text of a clicked button in the innercircle? @victorqribeiro

**Comment by victorqribeiro** [comment]
yes, everything is possible, I just don't have the time to do right now. but you can alter the icon of a button and then call the show method (that redraws everything).

I really can't right code right now, cause I'm working, otherwise I'd help you more.

**Comment by Yannick-DG** [comment]
All good, tried a few things with fillText, but seems like I cannot add it to the inner circle. Maybe you got Discord or another communication channel which talks a bit easier after work if you want? I'll be able to contribute but I need some directions in the code.

**Comment by victorqribeiro** [comment]
I just can't right now, sorry. Besides my full time job I'm working on some other things. Sorry.
